version: '3.8'

services:
  app:
    build:
      context: ./APP
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "5000:5000"
    volumes:
      - ./APP:/app
    depends_on:
      - db

  db:
    build:
      context: ./InfraBD
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: faat
      POSTGRES_PASSWORD: faat
      POSTGRES_DB: northwind
    ports:
      - "2000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# docker-compose up --build